apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: {{ .Release.Name }}-samba
    use: public
  name: {{ .Release.Name }}-samba-public
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: {{ .Values.volume.public.size }}
  hostPath:
    path: {{ .Values.volume.public.hostPath }}
    type: Directory
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
