apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: {{ .Release.Name }}-samba
    use: share
  name: {{ .Release.Name }}-samba-share
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: {{ .Values.volume.share.size }}
  hostPath:
    path: {{ .Values.volume.share.hostPath }}
    type: Directory
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
