apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: {{ .Release.Name }}-samba
    use: timemachine
  name: {{ .Release.Name }}-samba-timemachine
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: {{ .Values.volume.timemachine.size }}
  hostPath:
    path: {{ .Values.volume.timemachine.hostPath }}
    type: Directory
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
