apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ .Release.Name }}-samba
  name: {{ .Release.Name }}-samba-share
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.share.size }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-samba
      use: share
  storageClassName: ""
  volumeMode: Filesystem
