apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ .Release.Name }}-samba
  name: {{ .Release.Name }}-samba-share
type: Opaque
data:
  share: {{ .Values.sharePass | default "share" | b64enc }}
