apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ .Release.Name }}-samba
  name: {{ .Release.Name }}-samba-timemachine
type: Opaque
data:
  share: {{ .Values.timemachinePass | default "timemachine" | b64enc }}
