apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-samba
  name: {{ .Release.Name }}-samba
spec:
  ports:
  - port: 445
    protocol: TCP
    targetPort: 445
  selector:
    app: {{ .Release.Name }}-samba
  type: ClusterIP
