apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: {{ .Release.Name }}-unifi
    use: data
  name: {{ .Release.Name }}-unifi-data
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: {{ .Values.volume.data.size }}
  hostPath:
    path: {{ .Values.volume.data.hostPath }}
    type: Directory
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
