apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ .Release.Name }}-unifi
  name: {{ .Release.Name }}-unifi-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.data.size }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-unifi
      use: data
  storageClassName: ""
  volumeMode: Filesystem
